### ISSUE TITLE
JupyterLab instance is not picking up the google drive client id

### ISSUE THREAD

**Issue by krokha72** [jupyterlab/jupyterlab-google-drive#100]
I am using JupyterLab installation (v 0.28.12) on Ubuntu 16.04 with GDrive extension.
And I was following https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/advanced.md create google drive clientID and configure JupyterLab Gdrive settings.
Unfortunately JupyterLab Gdrive extencion is not picking up clientID override. it's coming up with Google API Error :  Not a valid origin for the client.. and message lists clientID different from what I configured.

**Comment by ian-r-rose** [comment]
Hi @krokha72,
It does seem like the settings system is not picking up the client ID that you are trying to set. A couple of things to try:
1. Have you tried setting the client ID from within the JupyterLab UI? That is to say, if you go to the `Google Drive` section of the settings editor (File --> Settings), and enter the data there, does it work?
2. A couple of days ago we made the description in `advanced.md` more detailed. Are you operation off of those more up-to-date docs? If so, we also welcome feedback in how to make them clearer.

**Comment by krokha72** [comment]
Hi Ian,
I appreciate your input 
1) I did try to override clientID both ways as described in advanced.md /1/ using UI and /2/ replacing drive.json. I got same issue both ways) 
2) advanced.md is very detailed. I would like to clarify one aspect though https://console.developers.google.com/apis/credentials?project=my-project allows you to download clientID json-file (drive.json), the downloaded file format differs in format from what you describe in doc for drive.json, its difference between {"clientId:"xxxx.apps.googleusercontent.com"} and {"web": {"clientId":"...", "project_id":"..", "auth_uri":...}}. I actually tried both formats and got same issue, but you may want to clarify it doc which format is acceptable for JupyterLab drive extension.
Is there any other workaround you may suggest?
Thanks
Alex

**Comment by ian-r-rose** [comment]
The `.json` file that you download from `console.developers.google.com` is of a different format than the one we expect in lab (`client_id` vs `clientId`, different structure, etc). You wan the file to be of the form
```json
{
    "clientId": "your.long.id.apps.googleusercontent.com"
}
```

If you edit it using the UI, it should automatically be stored in the right place.

**Comment by krokha72** [comment]
Jan,
thanks a lot for update. as I mentioned I have tried to find work around
the issue including using JupyterLab UI to enter override for clientId - it
did not work for me, the jupyter did not pickup given clientId
I am reinstalling google-drive extension anew now to check if reinstall
helps to resolve the issue
I will let you know
Thanks
Alex

**Comment by krokha72** [comment]
JupyterLab (server) picks up correct clientId from UI. So this issue is closed - thanks
I still have gdrive error "Not a valid origin for the client https://xx.xx.xx.xx:8888 has not been whitelisted for client ID.." , I am trying to figure out the reasons

**Comment by ian-r-rose** [comment]
Okay. Let me know if any part of the `advanced.md` instructions are unclear so we can try to improve them.
