### ISSUE TITLE
es6-promise issue causes blank screen

### ISSUE THREAD

**Issue by brianray** [jupyterlab/jupyterlab-google-drive#103]
Just installed jupyterlab-google-drive.

```
index.out.js:1 Uncaught Error: Cannot find module "es6-promise/auto"
    at webpackMissingModule (index.out.js:1)
    at Object.<anonymous> (index.out.js:1)
    at __webpack_require__ (bootstrap bc4b16e0710ff2e07011:49)
    at bootstrap bc4b16e0710ff2e07011:147
    at main.bundle.js:151```

Google Chrome Version 62.0.3202.89 (Official Build) (64-bit)
@jupyterlab/google-drive v0.8.0
jupyterlab                0.29.1                   py35_0    conda-forge
jupyterlab_launcher       0.5.5                    py35_0    conda-forge

I did see reference to this code here:

https://github.com/jupyterlab/jupyterlab-google-drive/blob/43fed700de1376da3fbafc06637f068927bb109a/test/karma-auth.conf.js

**Comment by ian-r-rose** [comment]
Ouch, that's unexpected. What leads you to think it is related to `karma-auth`? The error message looks like it is complaining about a missing `es6-promise` module.

What browser/OS are you using?

**Comment by brianray** [comment]
I am using OSX EL Capitan 10.11.6. The same behavior happens on Safari browser.

When I uninstall the extesion I get this error https://gist.github.com/brianray/e44f92c0982073c25682c5a6eeffdf99

Then, it thinks it is uninstalled:

(py3k) USATLBRRAYMB:ER_admission brray$ jupyter labextension uninstall @jupyterlab/google-drive
No labextension named "@jupyterlab/google-drive" installed

Still blank screen.

I conda remove and install jupterlab. Still blank screen

**Comment by ian-r-rose** [comment]
Did v0.29 work correctly before you installed the extension? Seems like it might be an issue with the bundling step with JupyterLab. @blink1073, do you have any idea what might be happening here?

**Comment by brianray** [comment]
If go back to 27, no blank screen.

Then update to 29:

   jupyterlab: 0.27.0-py35h269f579_2 --> 0.29.1-py35_0 conda-forge

no blank screen.

Then I jupyter labextension install @jupyterlab/google-drive, blank screen.

Also there are errors during install:

https://gist.github.com/brianray/8432fe55a6b98328dd6d20ea3197d8ea

Makes me wonder what the labextension installer is clobbering.

**Comment by ian-r-rose** [comment]
I can't reproduce this issue on my machine, but can you check what happens if you install this branch?
https://github.com/ian-r-rose/jupyterlab-google-drive/tree/include-es6-promise

You would checkout the branch, then from the repo directory enter
```
jupyter labextension install .
```

**Comment by brianray** [comment]
Same result https://gist.github.com/brianray/d6f55bbd0730f5567f899d073fced521
