### ISSUE TITLE
chat functionalities without gg drive

### ISSUE THREAD

**Issue by yougha54** [jupyterlab/jupyterlab-google-drive#104]
google drive is blocked by my company, is it a way to provide chat functionnality without google drive

**Comment by ian-r-rose** [comment]
Unfortunately not at the moment. All the realtime communication is done through Google Drive. We are working on a self-hosted solution, but that will take some time.

**Comment by yougha54** [comment]
Le 20 nov. 2017 15:48, "Ian Rose" <notifications@github.com> a écrit :

Unfortunately not at the moment. All the realtime communication is done
through Google Drive. We are working on a self-hosted solution, but that
will take some time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jupyterlab/jupyterlab-google-drive/issues/104#issuecomment-345717183>,
or mute the thread

**Comment by ian-r-rose** [comment]
Google Drive no longer allows third-party realtime applications, so this is now moot.
