### ISSUE TITLE
Sign-in process doesn't complete

### ISSUE THREAD

**Issue by philipsd6** [jupyterlab/jupyterlab-google-drive#105]
When I launch JupyterLab, and then launch my browser with the given URL, I then click on the Google SIGN IN button. The "Choose an account" pop-up appears, and I select my account.  Then the pop-up disappears and the Google Drive tab remains the same. It doesn't update with anything -- the SIGN IN button is still there.

If I select "use another account" the flow goes through the login process, but the same end is met.

There are no errors in the Javascript console.

**Comment by ian-r-rose** [comment]
Sometimes privacy plugins can interfere with the login process. Try disabling things like blocking third party cookies if you have any enabled.

What browser/OS are you using?

**Comment by philipsd6** [comment]
That was the problem -- Either Privacy Badger or uBlock Origin. I disabled both and it worked, I re-enabled and it failed. I disabled Privacy Badger for the site (localhost:8888) and it worked again.

**Comment by ian-r-rose** [comment]
Glad to hear it!

**Comment by philipsd6** [comment]
Sadly, as uBlock Origin is force installed by corporate group policy, I cannot keep it disabled for long before the problem recurs.

**Comment by ian-r-rose** [comment]
Can you add exceptions to the whitelist? You may want to try allowing `accounts.google.com` (or similar) to get through.

**Comment by philipsd6** [comment]
The Google Chrome settings and plugins are locked down and not configurable, but I modified the registry keys to suit my purposes and then denied privs to those keys from SYSTEM and that _should_ keep them the way I need them. Otherwise I cannot add to the whitelist, nor allow third party cookies.
