### ISSUE TITLE
google-drive@0.10.0" is not compatible with the current JupyterLab

### ISSUE THREAD

**Issue by nmeraihi** [jupyterlab/jupyterlab-google-drive#117]
I'm trying to install Google Drive in my JupyterLab. I did all the steps listed [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/advanced.md#Realtime-API) but Is still have this error:
```bash
"@jupyterlab/google-drive@0.10.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.10.0-0 <0.11.0-0    >=0.14.0-0 <0.15.0-0 @jupyterlab/application
>=0.10.0-0 <0.11.0-0    >=0.14.0-0 <0.15.0-0 @jupyterlab/apputils
>=0.10.0-0 <0.11.0-0    >=1.0.1-0 <2.0.0-0   @jupyterlab/coreutils
>=0.10.0-0 <0.11.0-0    >=0.14.0-0 <0.15.0-0 @jupyterlab/docmanager
>=0.10.0-0 <0.11.0-0    >=0.14.0-0 <0.15.0-0 @jupyterlab/filebrowser
>=0.10.0-0 <0.11.0-0    >=0.14.0-0 <0.15.0-0 @jupyterlab/rendermime
>=0.49.0-0 <0.50.0-0    >=1.0.1-0 <2.0.0-0   @jupyterlab/services
```

**Comment by ian-r-rose** [comment]
Hi @nmeraihi, it looks like you are using an older version of JupyterLab (v0.27 if memory serves). The current version of `@jupyterlab/google-drive` is for JupyterLab v0.31. If you cannot upgrade your JupyterLab, you can specify the version of `@jupyterlab/google-drive` for that [release](https://github.com/jupyterlab/jupyterlab-google-drive/releases/tag/v0.6.0):
```bash
jupyter labextension install @jupyterlab/google-drive@0.6`
```

**Comment by ian-r-rose** [comment]
@nmeraihi Did you get this working?

**Comment by ian-r-rose** [comment]
Closing this as answered. If you continue to have troubles with this, feel free to reopen.
