### ISSUE TITLE
Google API Error 

### ISSUE THREAD

**Issue by momonala** [jupyterlab/jupyterlab-google-drive#121]
Hi, I got the following error on running `jupyter lab` after installation of `jupyter labextension install @jupyterlab/google-drive`. When I open the GUI, it says Google API Error, and there is no way for me to log onto my Google Drive account. The text editor works fine. 

I got the following `warning` on intallation of the G-drive extension, but the message ended with a `success`. I am on Windows 10. Let me know if there is a known solution to this. Thanks! 
```
warning Error running install script for optional dependency: "C:\\Users\\mohit\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: C:\\Users\\mohit\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas\nOutput:\nC:\\Users\\mohit\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Users\\mohit\\Anaconda3\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.9.1 | win32 | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Can't find Python executable \"C:\\Users\\mohit\\Anaconda3\\python.EXE\", you can set the PYTHON env variable.\ngyp ERR! stack     at PythonFinder.failNoPython (C:\\Users\\mohit\\Anaconda3\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:483:19)\ngyp ERR! stack     at PythonFinder.<anonymous> (C:\\Users\\mohit\\Anaconda3\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:508:16)\ngyp ERR! stack     at C:\\Users\\mohit\\Anaconda3\\node_modules\\npm\\node_modules\\graceful-fs\\po

success Saved lockfile.
Done in 39.42s.
```
![error](https://user-images.githubusercontent.com/16393105/35091596-465fb586-fc3d-11e7-974c-d8d7f1f1a785.png)

**Comment by ian-r-rose** [comment]
Thanks for the report @momonala. The Google authentication process relies on the `localStorage` and `sessionStorage` browser APIs, which are sometimes blocked by browser security settings. It looks like you are using Firefox. Can you try to temporarily disable any cookie/tracking blocking for JupyterLab to see if that fixes the problem? If so, you may need to add an exception to your settings somewhere.

**Comment by momonala** [comment]
It looks like changing the `Accept 3rd Party Cookies` from 'visted' to 'always' did the trick. Thanks!

**Comment by ian-r-rose** [comment]
Great! If you want to re-enable those settings, it may work to add an exception for `accounts.google.com`.
