### ISSUE TITLE
"Not a valid origin for the client:" - Localhost keeps changing? 

### ISSUE THREAD

**Issue by FMCumhaill** [jupyterlab/jupyterlab-google-drive#122]
`Not a valid origin for the client: http://localhost:8801 has not been whitelisted for client ID 21290814895-9fv27t42oudag836e35t084dblpkh8ad.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID.`

I'm using the google drive plugin  on an anaconda installation. I've had it working fine, but recently I started seeing this error when I opened up jupyter labs. 

When this error appears, the google drive tab only shows a logo and has no functionality. If I remove my client ID from the setting tab, I can access my google drive, but not collaborate. 

I've tried white listing my URL, (https://localhost:something). Each time I whitelist a url, jupyter labs just connects on another port. 

Any suggestions?

**Comment by ian-r-rose** [comment]
The whitelist that you specify on the Google developer console is independent of the port that JupyterLab chooses to launch. Is it possible that you have extra notebook servers running that are preventing you from launching on the port you want? You can check that by running
```bash
jupyter notebook list`
```
on the command line.

**Comment by FMCumhaill** [comment]
Yes it would appear I have 6 notebooks running.... 

What would the command be to quit them all?

**Comment by ian-r-rose** [comment]
You can run `jupyter notebook stop <port>` to stop a specific one. I am not sure if there is a command to stop all of them,

**Comment by ian-r-rose** [comment]
@FMCumhaill Did you get this working?

**Comment by ian-r-rose** [comment]
Closing this as answered. If you continue to have troubles, feel free to reopen.

**Comment by FMCumhaill** [comment]
Hey sorry got caught up with something else. 

Can you check the syntax of that command,  "jupyter notebook stop <port>" 
I remove the < > and input the port (8888) and get an error 
`[C 13:54:02.782 NotebookApp] No such file or directory: C:\Users\Fionn Delahunty\stop`
