### ISSUE TITLE
Sign in appears to be successful, but no File Browser

### ISSUE THREAD

**Issue by resero-labs** [jupyterlab/jupyterlab-google-drive#127]
I've recently installed and configured the google-drive extension (while the realtime api has been deprecated, I'm still able to enable it). 

When I start the server, there is a google drive tab. When I select "Sign In" from that tab, I'm presented with a "Choose Account" pop-up and I select the account that I've configured client_id and enabled realtime API. It appears to be successful, but when the pop-up is dismissed, the Drive tab does not present a file browser, rather the "Sign In" button remains.

There isn't any status printed to either the console on the server or the JS console in the browser. 

The following warning message is presented in the JS Console in the browser: "index.js:58 Warning: Google Realtime has been deprecated. No new realtime applications may be registered, and existing ones will cease to work in December 2018"

Running Version 0.31.5, in a docker container (ubuntu) on OSX.

**Comment by ian-r-rose** [comment]
When you say you are still able to enable the realtime API, what do you mean? I wonder if the fact that you have tried to enable it when new applications using it cannot be registered is causing a problem.

**Comment by resero-labs** [comment]
I followed the instructions in advanced.md. When I got to step 8 (enable Google Drive API, Google Picker API), I decided to try enabling the Google Realtime API as well, figuring that if it wasn't available for new apps, the "enable api" button wouldn't be available. Also looking at the dashboard it appears that the Realtime API is enabled and active (see attached image).
![screen shot 2018-02-14 at 9 23 15 am](https://user-images.githubusercontent.com/35940335/36215330-0a13881e-1169-11e8-95b0-16bdc19dbcf1.png)

**Comment by ian-r-rose** [comment]
Can you try without the Realtime APIs? I am not confident that a new webapp with them enabled would work correctly, even if it does allow you to select them.

**Comment by resero-labs** [comment]
After disabling the Realtime API, and restarting the server, I now see the file browser. 

I was able to create a document (see ![screen shot 2018-02-14 at 10 59 19 am](https://user-images.githubusercontent.com/35940335/36219924-2edf15b6-1176-11e8-8349-71529b554616.png)
).

However, I'm unable to edit the document.

The following errors show up in the browser's JS Console (see 
![screen shot 2018-02-14 at 10 59 29 am](https://user-images.githubusercontent.com/35940335/36219958-4add1452-1176-11e8-9db9-a7c5238b6676.png)
)

**Comment by ian-r-rose** [comment]
Those look like Realtime API errors. I think the "access denied" errors are expected, since you have set up the app after it has been disabled. Can you make sure that `realtime: false` is set in the settings, as described [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/advanced.md#realtime-api)?

**Comment by resero-labs** [comment]
I hadn't overriden the global realtime setting of true. I've done so and am now able to edit notebooks stored on google-drive.

**Comment by ian-r-rose** [comment]
Glad to hear it!
