### ISSUE TITLE
Error starting kernel

### ISSUE THREAD

**Issue by ck2136** [jupyterlab/jupyterlab-google-drive#129]
Hello!

I keep getting this error whenever I come back to my jupyter lab and open up a previously worked-on notebook.

so when I open a previous notebook it asks for the kernel:

![image](https://user-images.githubusercontent.com/21317713/37869660-f08ddfe8-2ffe-11e8-97fb-41854cc941d0.png)

Then immediately I get this error:
![image](https://user-images.githubusercontent.com/21317713/37869662-0a6c9d32-2fff-11e8-9c93-66467a1047f1.png)

Now if I try to open a classic notebook:
The notebook shows a kernel error:
![image](https://user-images.githubusercontent.com/21317713/37869680-5f90c090-2fff-11e8-97e5-dfdf809eeb6d.png)

How should I remedy this?  Currently I'm just manually restarting the jupyter lab on the command line.
I'm running the jupyter lab on Ubuntu 17.10 Thank you!

**Comment by ian-r-rose** [comment]
Hi @ck2136, is this when using the Google Drive plugin, or is it when editing a file on your local drive?
If it's the second, can you reopen this question on the main JupyterLab repository?

Also, it would be helpful if you include the full error message. It looks like there is more of the error further down the scroll in your image.

**Comment by ck2136** [comment]
Hi!

The error message would disappear before I could take a snap shot so I couldn't scroll down. But the command line output is as below:

```
kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/manager.py", line 239, in start_kernel
        self.write_connection_file()
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/connect.py", line 472, in write_connection_file
        kernel_name=self.kernel_name
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/connect.py", line 137, in write_connection_file
        with open(fname, 'w') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1000/jupyter/kernel-7b8e8be3-efb2-41af-92d4-0c97a5cc915e.json'
[W 04:31:39.392 LabApp] Unhandled error
```

**Comment by ck2136** [comment]
I've updated jupyter using:

```
pip install --upgrade jupyter
```
based on  [#1601](https://github.com/jupyterlab/jupyterlab/issues/1601) from the jupyter lab issues page.

I usually see the error happening when I relaunch and let it sit for a day. Let's see if it happens tomorrow! Hopefully I'll get to close this

**Comment by ian-r-rose** [comment]
Again, is this related to the Google Drive plugin (this repository), or is it with the core of JupyterLab?

**Comment by ck2136** [comment]
Sorry, this is a issue of JupyterLab as a whole! Just didn't know how to migrate this issue over there!
