### ISSUE TITLE
Browser sensitivity? And whitelisting.

### ISSUE THREAD

**Issue by pavelgetmyle** [jupyterlab/jupyterlab-google-drive#139]
Hey guys,

First of all, thanks for the amazing tool, it's extremely helpful to sync files automatically.

Now, a couple of questions:
1. Does it work with Opera?
2. Where should I change Client_ID?
I've walked through all the setting items, and finally got the below. There is Google Drive now, however it doesn't work and asks for the whitelising of the Client_ID. I put the client ID in drive.json at share/jupyter/lab/schemas/@jupyterlab/google-drive and the "Sign In" button appears (though it didn't work - Error 400). After Jupyterlab restarting the Clien_ID disappeared from the drive.json and I've got the below.
Any advice on where and how to fix it would be very appreciated.
Thanks a lot!

![image](https://user-images.githubusercontent.com/7799626/44482749-7bb0d080-a606-11e8-86ee-c11dd106d364.png)

**Comment by pavelgetmyle** [comment]
One more things. When trying to put the client_ID directly (the right field) - the "diskette" is gray and it doesn't work, and an error message appears at the bottom-right

![image](https://user-images.githubusercontent.com/7799626/44483501-7eacc080-a608-11e8-9c20-f2a5da2ca357.png)

**Comment by ian-r-rose** [comment]
Hi @pavelgetmyle, sorry for the slow reply. Unfortunately, the realtime syncing of this plugin is going away, thanks to Google. The storage aspect will remain the same. To your specific questions:
1. I have not tested it in Opera, which is not on the list of supported browsers for JupyterLab. It may or may not work, I'm not sure.
2. You should add make sure that you add the client id using the advanced settings editor UI (i.e., not editing the file on disk). When you add it there, it should be valid JSON. There is an error message at the bottome left of you screenshot indicating a parsing error with what you have put in. It should look something like:
```json
{
  "clientd": "your_id",
  "realtime": false
}
```
