### ISSUE TITLE
Backup folder

### ISSUE THREAD

**Issue by setegonz** [jupyterlab/jupyterlab-google-drive#144]
I'm not able to view a specific folder through the extension. That folder is my desktop's backup. Am I doing something wrong?
![946e8dee-850d-4cb2-991d-f3cb52f35179](https://user-images.githubusercontent.com/11341688/48666844-cf6d7180-eab0-11e8-83b5-ddb51bab1f22.png)
![7066fc93-8703-443e-8c0d-0e9eeebd6779](https://user-images.githubusercontent.com/11341688/48666848-d4322580-eab0-11e8-9f57-0a6a24a3bdb0.png)

**Comment by ian-r-rose** [comment]
Hi @setegonz, which folder are you referring to? In general, this extension exposes the root of a user's Google Drive, as well as Team Drives and items that have been shared with them. I am not aware of a Google Drive API for system backups.

**Comment by setegonz** [comment]
Hi @ian-r-rose. As seen in the first photo, I have a folder in my office computer linked to my google drive inside the "computers" folder. That folder doesn't appear through the jupyter lab google drive extension (2nd pic).
