### ISSUE TITLE
File keep loading, but never loaded

### ISSUE THREAD

**Issue by uremember809** [jupyterlab/jupyterlab-google-drive#146]
I have the plugin installed and configured, the file showed in the list. I can even create and delete files. However, when I tried to open a file, any file, it just keep loading, and never got loaded.

**Comment by ian-r-rose** [comment]
Hi @uremember809, sorry for the slow response. What version of @jupyterlab/google-drive are you using? Google just shut down their realtime service, and you may have gotten caught up in that. I have published a new version that strips out any realtime integration (v0.16.0) to respond to that, and earlier versions may run into troubles.

**Comment by uremember809** [comment]
I don't know what version it is, I installed 2 weeks ago when I open this ticket.
I figured out a way to make it work. whenever I open the app, it won't load, I turn off the realtime switch, refresh, then it loads, I then turn the realtime back on. it seems work.
what you said is that realtime not actually work anymore, leave it on won't make any difference, right?
I think this ticket is closed then

**Comment by ian-r-rose** [comment]
The realtime switch has been removed, and things won't work reliably with it on. I recommend updating to version 0.16.0 (`jupyter labextension install @jupyterlab/google-drive@0.16.0`).

Closing as answered, thanks for following up @uremember809!

**Comment by ian-r-rose** [comment]
If you still run into troubles, feel free to comment here though!
