### ISSUE TITLE
can't read korean in ipynb files

### ISSUE THREAD

**Issue by yahwang** [jupyterlab/jupyterlab-google-drive#147]
Hello,
I can't read korean when viewing .ipynb files in my drive. Csv and txt files in drive only can be read in korean. However, I can read korean in downloaded ipynb files. 

Is there any way to solve this???

![image](https://user-images.githubusercontent.com/12381530/50881263-6c4eea00-1424-11e9-9909-5b36ce374808.png)

**Comment by ian-r-rose** [comment]
Hi @yahwang, thanks for the report, and I'm sorry to hear that! Can you share with me a notebook (possibly on GitHub) for which you see this problem? I'd like to have a good test case when working out a fix.

**Comment by yahwang** [comment]
@ian-r-rose Thanks for the reply. you can use my files in https://github.com/yahwang/python-note/tree/master/basics. all files contain korean.

**Comment by LongLVNH** [comment]
This happens to me as well with jupyterlab from Anaconda 2018.12 for Windows and OSX with spanish characters: "áéíóúñ¡¿".

**Comment by ian-r-rose** [comment]
Thanks for the report @LongLVNH, I am working up a fix, but the Google APIs are fighting back :confused:

**Comment by LongLVNH** [comment]
Awww that is sad. And I was thinking it was due to Google API actually. Anyway thank you very much for your time. I will get organised with my friend to write in English meanwhile.

**Comment by ian-r-rose** [comment]
I hope to get a fix out soon, sorry for the troubles!

**Comment by LongLVNH** [comment]
Do not be sorry. Instead I am thankful to you and people like you because I am able to do so much cool stuff thanks to your dedication. For the time being, while the fix comes up, I will get around the problem. =)

Thank you for your time.

**Comment by ian-r-rose** [comment]
Hi @yahwang, @LongLVNH, sorry to take so long to work out a fix for this! I've just published a prerelease of this extension, targeting the current JupyterLab prerelease. Could you check to see if it solves your problem? If you are on the previous JupyterLab, you would upgrade by entering
```
pip install --upgrade --pre jupyterlab
jupyter labextension install @jupyterlab/google-drive@next
```

**Comment by yahwang** [comment]
@ian-r-rose Thanks for fixing the issue. It works after upgrade!
my env : ubuntu 18.04 / python 3.6.7( with pyenv ) /  jupyter 1.0.0a1

**Comment by ian-r-rose** [comment]
Great, thanks for checking @yahwang!

**Comment by LongLVNH** [comment]
Sorry for the delay. I needed to update some stuff and also was a little busy. It works so great for me. I was having some issues with Ghostery extension but was able to see that the issue was fixed after disabling it.

Thank you very much for your time !!!

**Comment by ian-r-rose** [comment]
Thanks for checking @LongLVNH ! Under 24 hours is plenty quick :)
