### ISSUE TITLE
How can I create new notebook documents within the Drive tab?

### ISSUE THREAD

**Issue by tamama** [jupyterlab/jupyterlab-google-drive#154]
Hi,

May I know how can I create new notebook documents directly from the Drive tab? It keeps ending up into my jupyter workspace folder.

Kind regards,
Tamama

**Comment by bmshouse** [comment]
This extension does not attach Google Drive to the file-system. It provides an interface for files to be copied to and from Google Drive in the JupyterLab interface.  If you want to attach Google Drive to the file-system you would need to use something like [google-drive-ocamlfuse](http://gdfuse.forge.ocamlcore.org/).
