### ISSUE TITLE
Error: 500 (internal server error)

### ISSUE THREAD

**Issue by patchie** [jupyterlab/jupyterlab-google-drive#155]
When trying to install your extension via the jupyterlab extension manager, i get the following error: "Error: 500 (internal server error)"

Screenshots below:
![image](https://user-images.githubusercontent.com/1792727/55881434-f3863800-5ba2-11e9-9ac3-e8cbaba09be7.png)

![image](https://user-images.githubusercontent.com/1792727/55881456-fe40cd00-5ba2-11e9-8aea-1e1b2ecca86d.png)

**Comment by vidartf** [comment]
Is this error still appearing? If so, you might be able to see more information in the server logs (especially if you start jupyter lab with the `--debug` flag). Also: Does it also fail if you run `jupyter labextension install @jupyterlab/google-drive` on the command line?
