### ISSUE TITLE
access data on google drive

### ISSUE THREAD

**Issue by yee379** [jupyterlab/jupyterlab-google-drive#156]
is there a way to access data that is stored on google drive from the notebook?

i am able to store and access my notebooks on google drive, but it would be useful to access (small) data that i keep on gdrive.

**Comment by martinorpa** [comment]
Follow the instructions on the following link,

https://medium.com/@umdfirecoml/a-step-by-step-guide-on-how-to-download-your-google-drive-data-to-your-jupyter-notebook-using-the-52f4ce63c66c

Remenber, when you create OAuth 2.0 client IDs to use with Jupyer choose "other", 
neither Web application, nor  Chrome App Learn more, but dont know iOS or Android may be. 

check this link as reference, in case: https://stackoverflow.com/questions/12710262/google-drive-redirect-uri-mismatch

**Comment by danielmlow** [comment]
So there's no way to do this (i.e., load files without downloading them)?

```
import os
os.listdir('GDrive://My Drive/')

**Comment by bmshouse** [comment]
Currently, you would need to use [OCAML Fuse](https://github.com/astrada/google-drive-ocamlfuse) to mount Google Drive to the filesystem. Then you can treat it just like any other file on the filesystem.

**Comment by bmshouse** [comment]
@yee379 I am going to close this ticket because it is beyond the scope of this JupyterLab widget. 

Please let us know if we can provide any other assistance.
