### ISSUE TITLE
Google Oauth Setup procedure does not work anymore (at least for Europe?)

### ISSUE THREAD

**Issue by jpdus** [jupyterlab/jupyterlab-google-drive#157]
Hi there,

I am from Germany (don't know whether this issue applies worldwide or only for European users due to GDPR) and I am not able setting up the extension using [your guide](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/setup.md).

The configuration for the OAuth screen looks very different and prevents me from entering any non-top-level-domains (e.g. http://localhost:8888 like in your example , also without http/https and port).

The error message is: "Ungültige Domain: muss eine private Top-Level-Domain sein." (Not a valid domain - private top-level domain necessary) with a link to [this site](https://github.com/google/guava/wiki/InternetDomainNameExplained#public-suffixes-and-private-domains).

There are also necessary fields for a "link to startpage of application" and "link to privacy notice of application" which both need to be hosted on an authorized domain. - see screenshot (German) attached.

Is there any way to get it working on localhost and/or a fixed IP (without a domain)?

Thank you, great work with this extension!

![google_oauth_problem](https://user-images.githubusercontent.com/2862336/58429170-4493b200-80a5-11e9-998f-fe8d8c21415e.png)

**Comment by ian-r-rose** [comment]
Yikes @jpdus, thanks for the report! I have not seen this before, and am unaware of restrictions on using `localhost` as an expected origin. I suspect you are right -- some variety of GDPR restriction may be the culprit here.

If that is the case, I'm not really sure what could be done. We have no real control over the security policies set by Google here, and they have a bit of a history of changing them without notice or recourse. In this particular case, you may be out of luck without your own top-level domain to be verified :slightly_frowning_face:

**Comment by bmshouse** [comment]
@jpdus It might be worth checking out the service: xip.io

For example: 127.0.0.1.xip.io would resolve to 127.0.0.1 and may be able to work you around the restrictions. 

http://127.0.0.1.xip.io:8888/ is effectively the same thing as http://localhost:8888/

**Comment by bmshouse** [comment]
@jpdus The setup process has been updated to include more modern instructions for the Google OAuth process. Are you still working with this or is it safe to close the issue?

**Comment by jpdus** [comment]
@bmshouse I didn't try it again so far (as I was busy with other projects) but will try out soon. If there are no other bug reports, I think it's safe to close this issue. Many thanks, appreciate your project!

**Comment by bmshouse** [comment]
@jpdus I will close this issue, but if you run into trouble, please open another issue and I will work though it with you.

Thank you!
