### ISSUE TITLE
The Google Drive panel doesn't show a login button.

### ISSUE THREAD

**Issue by csevast** [jupyterlab/jupyterlab-google-drive#161]
I applied the setup instructions and I read the troubleshooting section. 

The browser console shows the following relative messages:
+ The resource from “http://localhost:8888/src/css/common.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). lab
+ Warning: no Client ID found. The Google Drive plugin will not work until the Client ID has been set, and the page refreshed.

**Comment by csevast** [comment]
I added both http://localhost:8888 and http://127.0.0.1:8888 and the `sign in` button became visible. After that, clicking on it raises another error:
```
400. That’s an error.

Error: invalid_request

Permission denied to generate login hint for target domain.
Request Details

That’s all we know.
````
I suppose that it is something in the settings Google Developer Console.
Can you help me?

**Comment by bmshouse** [comment]
@csevast Did you get this working, make progress, or give up?  The "no Client ID" found is a critical problem that can be resolved by getting the Client ID from your Google setup and putting it in the on-disk configuration file: `/home/jovyan/.jupyter/lab/user-settings/@jupyterlab/google-drive/drive.jupyterlab-settings`

The content should be something as follows with your Client ID replacing the example one provided:
```
{ "clientId": "0123456789012-abcd2efghijklmnopqr2s9t2u6v4wxyz.apps.googleusercontent.com"}
```

**Comment by csevast** [comment]
Ha! I gave up and I was not using Jupyter Lab in the last period, but now, after your message, I tried again and, as a miracle, it is working. May be it was a synchronization delay from google.

Thank you very much for your support.

**Comment by ian-r-rose** [comment]
Thanks for all your help on this (and other issues) @bmshouse!

**Comment by bmshouse** [comment]
@ian-r-rose The least I can do for all the work you have put into this and headache it is going to save me. :1st_place_medal:

**Comment by bshouse** [comment]
@csevast If things are working properly, would you please close this issue?  Thank you.
