### ISSUE TITLE
Google Drives API

### ISSUE THREAD

**Issue by bmshouse** [jupyterlab/jupyterlab-google-drive#164]
I suspect you are aware of this, but did not see it reflected in the Documentation. Google will be replacing all the existing Drive, Team Drive, and Picker APIs with a Drives API { https://cloud.google.com/blog/products/application-development/upcoming-changes-to-the-google-drive-api-and-google-picker-api }. The old APIs will be "turned off" on June 1st, 2020 and only the unified Drives API will remain.

**Comment by ian-r-rose** [comment]
Thanks for the ping on this @bmshouse, I was not, in fact, aware. This... will take some work.

**Comment by ian-r-rose** [comment]
Ultimately, the simplification in the Team Drives API is probably a good thing.  It's pretty messy and bolted on at the moment. I don't look forward to converting, though :/

**Comment by bmshouse** [comment]
Well, I wish I could help with the coding, but I dare not touch that. However, I can monitor the Issues here and try to help. Once I get my instance running, I will also update the setup.md with new screen shots and submit a pull. Hopefully, this will help free you up so you can focus on the real challenges.

**Comment by ian-r-rose** [comment]
I appreciate the help!

**Comment by elgalu** [comment]
Hey guys, so this Google Drive <-> JupyterLab integration will stop working in 4 months?

**Comment by bmshouse** [comment]
I have not looked closely enough at the code to make a good assessment of the impact. If Google keeps to their word, this extension will fail (at least partially).  In the best case scenario, it will work where the shutdown APIs are not used.

**Comment by ian-r-rose** [comment]
Hopefully we can keep things working here, though there may be some rocky times for people who are using the Team Drives feature (especially as I currently have no way of testing it :/ )

**Comment by bmshouse** [comment]
@ian-r-rose I have access to a few team drives, but they are limited to users within my university's domain. So, while I cannot give you access, I am happy to provide testing. Please let me know how/when I can assist.  Thank you for all your work on this project! I wish I could contribute more.

**Comment by bmshouse** [comment]
I just got an email from Google that states that the Google Picker API support for Google Drive will continue for the foreseeable future.

```
Hello Google Picker API developer,

We are writing to let you know about upcoming changes to the Google Picker API. We are contacting you because you use one or more apps connected to the Google Picker API.

What do I need to know?
Starting March 31, 2021, the Google Picker API will no longer support views and interactions with the following Google services:

Google Photos
Google Maps
YouTube
Google Image Search
Google Video Search
Webcam view (to record videos or take photos using a web camera).
The Google Picker API integration with Google Drive will remain unchanged and your application will continue to operate.

What Action do I need to take
If your applications use the Google Picker API integration for any of the services listed above, you will need to migrate your existing Picker integration to our modern APIs targeted for each specific application:

Photos API
Maps API
YouTube API
Custom Search API (supports Image & Video Search)
```
