### ISSUE TITLE
Can't files or folders in Drive "panel"

### ISSUE THREAD

**Issue by marmot2019** [jupyterlab/jupyterlab-google-drive#166]
I installed the extension and worked my way through creating a credential procedure as best as I can and I was able to "login" to Drive in JupyterLab.  But I only get an empty "panel" with none of my files or directories.  I also tried uploading a file where I get an error message saying that the file is "not valid save directory"  I also can't create a directory.  I don't know if two-part authentication is a problem or not.  I am using a Chrome Browser on Unbuntu 18.04 LTS.  Thanks in advance for any help! J

**Comment by bmshouse** [comment]
This one is going to be tough to troubleshoot with the information provided... Do you have any script blockers (NoScript, Brave, uBlock, etc) running that might be blocking cross site request or identification?  You might want to try to load JupyterLab (and the extension) with the Developer Tools frame open to see if there are any errors or failed network connections listed after the page has been load and the Google Drive tab activated.  Please let me know what you find I will try to get you going.  Thank you.

**Comment by bmshouse** [comment]
@marmot2019 I just wanted to follow up with you to see if there is any progress to report.
