### ISSUE TITLE
change file directory to google drive#save output

### ISSUE THREAD

**Issue by Yufei-Z** [jupyterlab/jupyterlab-google-drive#167]
how can I change file directory to google drive so that the result can be stored at drive? it can not find the folder "'GDrive:Shared with me/FINA4390"

**Comment by bmshouse** [comment]
Correct me if I am wrong, but it sounds like you want to save a file from you workspace directly to Google Drive. This extension does not offer any file-system integration. It provides way for you to easily copy files to and from Google Drive using the drag-and-drop interface. If you want to work directly on files in Google Drive, you would need to use something like [google-drive-ocamlfuse](http://gdfuse.forge.ocamlcore.org/) to mount your Google Drive on the local file-system. Another possibility would be using software to sync your local copy to Drive.

**Comment by bmshouse** [comment]
Closing issue as the request is beyond the scope of this project.
