### ISSUE TITLE
Unable to import files in jupyter lab

### ISSUE THREAD

**Issue by Picli** [jupyterlab/jupyterlab-google-drive#188]
Hello, I am unable to import files in jupyter lab. I am new to coding.

exits = pd.read_csv('GDrive:My Drive/Test/hourlyExits.csv',index_col='Station')
exits

This is the code I am using. Can you help me with the right path.

Error:
OSError: [Errno 22] Invalid argument: 'GDrive:My Drive/Test/hourlyExits.csv'

**Comment by bmshouse** [comment]
This extension does not mimic like a filesystem. It only allows you to copy files between Jupyter and Google. If you want to open a file, you would have to first drag-and-drop it into your workspace and open it from there. In order to use Google Drive like a regular filesystem, you would need to install something like [Google Drive OCAML Fuse](https://github.com/astrada/google-drive-ocamlfuse).

**Comment by Picli** [comment]
Thank you for the prompt response. I uploaded the file into the same directory as the notebook. But getting 'file not found error'[https://drive.google.com/file/d/17-EoRgFwJOFcW_726lKc7s7WNOciKlVb/view?usp=sharing](url)

**Comment by bmshouse** [comment]
I am a little confused. As I understand it you have two files: 1. a notebook, 2. a data file. You have used this extension to copy that data file to your local workspace with the notebook. Now you are trying to open the data file. The whole operation should now be happening outside of Google Drive. Is this an accurate description of the situation?

**Comment by Picli** [comment]
Yes. Got the access to create, delete, view, rename etc on google drive via Jupyter lab left side panel. Now I am trying to open the data file from local Jupyter lab but the 'file not found' error is presenting while the data file is in the same directory as the notebook. Tried many ways but could not figure out.

**Comment by bmshouse** [comment]
So, I guess I do not understand why you are getting `file not found` on a Google Drive url. Now that the file is local, you should be doing a `pd.read_csv('hourlyExits.csv',index_col='Station')`. Why is it looking for anything on Google Drive if everything is local?
