### ISSUE TITLE
cannot active plugin in jupyterlab 0.24.1

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#19]
index.js:268 Error: No provider for: jupyter.services.commandpalette.
    at JupyterLab.Application.resolveRequiredService (/lab/main.bundle.js:185355:35)
    at /lab/main.bundle.js:185313:70
    at Array.map (native)
    at JupyterLab.Application.activatePlugin (/lab/main.bundle.js:185313:38)
    at /lab/main.bundle.js:185439:26
    at Array.map (native)
    at JupyterLab.Application.start (/lab/main.bundle.js:185438:33)
    at main (/lab/main.bundle.js:130911:9)

**Comment by ian-r-rose** [comment]
This type of error usually occurs when you have a version-incompatible plugin. Can you verify that you are running `@jupyterlab/google-drive` v0.2.0?

**Comment by ktong** [comment]
it's 0.2.0.  0.1.1 cannot be installed due to imcompatible plugin

**Comment by ktong** [comment]
My env should be clean because it's built by docker. Will double check it later.

**Comment by ian-r-rose** [comment]
This is a tough one, though now I can reproduce your problem! If I create a new conda environment and install jupyterlab into it
```
conda create -n test -c conda-forge python=3 jupyterlab nodejs
source activate test
jupyter labextension install @jupyterlab/google-drive
jupyter lab
```
I see the same error as you. If I subsequently run
```
jupyter lab clean
jupyter lab build
```
it works as expected. I am not sure what is causing the error yet, but we are making progress!

**Comment by ktong** [comment]
thanks. Will add jupyter lab clean & build in docker as temporary workaround

**Comment by ian-r-rose** [comment]
Good catch, @ktong. It appears to have been a bug in the extension build system, and fixed in jupyterlab/jupyterlab#2483.

**Comment by ktong** [comment]
cool. thanks

**Comment by ktong** [comment]
It's solved in 0.25

**Comment by ian-r-rose** [comment]
:+1:

**Comment by nscozzaro** [comment]
@ian-r-rose I'm getting a similar error : `Error: No provider for: @jupyterlab/apputils:ICommandPalette` and I'm trying to figure out what could be causing it. 
However, it's a different situation: I'm building a custom JupyterLab extension, and started out by following the Astronomy Picture tutorial. I'm trying to use Webpack to create the bundle of the extension. In the extension there's an import
`import {ICommandPalette, MainAreaWidget, WidgetTracker} from '@jupyterlab/apputils';`, so from reading these Github issues threads could it be the case that the bundle is including a copy of `ICommandPalette` which then conflicts with JupyterLab's `ICommandPalette`? 
Please let me know if you have any suggestions.

**Comment by nscozzaro** [comment]
I ended up resolving this by using the `webpack-node-externals`  package:
```
var nodeExternals = require('webpack-node-externals');
const VueLoaderPlugin = require('vue-loader/lib/plugin');

module.exports = {
    entry: [
        './src/plugin.js'
    ],
    target: 'node', // in order to ignore built-in modules like path, fs, etc.
    externals: [nodeExternals()],
    output: {
        path: path.resolve(__dirname, 'lib'),
        filename: 'plugin.js',
        libraryTarget: 'commonjs-module'
    },
```

**Comment by ian-r-rose** [comment]
I confess I don't quite understand the shape of the solution, but thanks for following up @nscozzaro so that others may try it if they run into something similar.

**Comment by nscozzaro** [comment]
@ian-r-rose By default, Webpack includes all the code of dependencies in the bundle. However, you can tell it not to by putting `externals: [nodeExternals()]` in the webpack config. The generated bundle then relies on the external packages and you have to tell it where to find them. So I had `import {ICommandPalette, MainAreaWidget, WidgetTracker} from '@jupyterlab/apputils';`, and webpack-node-externals does tells webpack where to find '@jupyterlab/apputils', namely in the node_modules folder.
