### ISSUE TITLE
JupyterLab 3 support

### ISSUE THREAD

**Issue by tracek** [jupyterlab/jupyterlab-google-drive#190]
Do you have plans to support JupyterLab 3? I took a stab at it, but got stuck.

**Comment by bmshouse** [comment]
@tracek At this point there is no clear plan for JupyterLab 3 support. This project is a community project: I do my best to keep up with Issues. The owner does sanity checks, manages pull requests, and publishes official updates. @andrelfpinto was responsible for the JupyterLab 2.x support (Thank you!). It might be worth looking at the [pull request](https://github.com/jupyterlab/jupyterlab-google-drive/pull/173) for the migration between v1 -> v2 to see if it can offer any guidance.

**Comment by tmclerran** [comment]
I would also be very interested to see support for JupyterLab 3. Here's the migration guide from the official JupyterLab docs for migrating extensions from JupyterLab 2.x to 3.x. 
https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#jupyterlab-2-x-to-3-x

**Comment by jasongrout** [comment]
As a follow-up, JupyterLab 3.3 now has experimental real-time collaboration support using Yjs built in, and I think we plan to debut it as a core feature in JupyterLab 4.0.
