### ISSUE TITLE
404 after adding new file into google drive

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#24]
steps to reproduce:
  * go to google drive tab
  * clicking + button to add new python3 notebook

expected result:
  * notebook open with python3 kernel

actual result:
  * no kernel for notebook

error:
api:313 GET https://drive.google.com/otservice/bind?rctype=js&rcver=0&id=0B_5YP2zWaYhvO…JdrKkK_EeQ&lsq=1498760861991&VER=8&SID=3A50044AED02FAA9&AID=5&RID=rpc&CI=0 404 ()
api:453 Drive Realtime API Error: not_found: File not found.

**Comment by ktong** [comment]
workaround:
  save notebook immediately after creating notebook.

**Comment by ian-r-rose** [comment]
Hi @ktong, thanks for the report. I have just published a v0.3.0 release that has numerous bugfixes. Can you check if that fixes your problem?

As an aside, the underlying Notebook implementation in JupyterLab is undergoing a big rewrite at the moment, so things may be a little bit bumpy for the next couple of weeks.

**Comment by ian-r-rose** [comment]
Scratch that, v0.3.1 is the correct release, which may fix your problem.

**Comment by ktong** [comment]
yes, it looks fixed in 0.3.1

**Comment by ian-r-rose** [comment]
Great. Thanks for checking.

Closed via #17.
