### ISSUE TITLE
Only works when run with superuser permissions

### ISSUE THREAD

**Issue by SyxP** [jupyterlab/jupyterlab-google-drive#36]
When running Jupyter Lab after installing the extension, running jupyter lab will result in a 404.

However, it will work properly when running with sudo jupyter lab --allow-root.

**Comment by blink1073** [comment]
Hi @SyxP, this will be fixed in the next release of JupyterLab: https://github.com/jupyterlab/jupyterlab/pull/2697.

**Comment by ian-r-rose** [comment]
This should be fixed in `0.26` now.

**Comment by SyxP** [comment]
I verified thta the problem is indeed fixed in 0.26
