### ISSUE TITLE
Folder creation impatience bug

### ISSUE THREAD

**Issue by danpf** [jupyterlab/jupyterlab-google-drive#43]
If you're an impatient person like myself, or you just forgot the difference between the breadcrumb (double click) and the new folder button (single click) you might accidentally double click the new folder button.

in doing so you will create two folders with the same name. Because they are the same name you can only select them together, and they are difficult to delete (i had to login to drive separately to do it). Sometimes they are easy to delete though.  Only happens in google drive because it takes longer to make folders remotely.

Usually the first folder deletes, but yields an error in the pop-up box. then you have to delete the second folder.

**Comment by ian-r-rose** [comment]
Thanks for the report, @danpf. You are right, there are a couple of filebrowser actions that can be a bit awkward and buggy when the network delay is factored in.

**Comment by ian-r-rose** [comment]
Addressed by jupyterlab/jupyterlab#2748, which will be in the next release.

**Comment by ian-r-rose** [comment]
JupyterLab v0.27 has been released, which has this fix.
