### ISSUE TITLE
get 403 error from google drive api

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#46]
Access Google drive api  https://content.googleapis.com/drive/v3/files?xxxx returns 403 with exceed daily limit message below. But when I check the quota, it's far below the limit (7K vs 1G). Do I miss any configuration?

```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

**Comment by ian-r-rose** [comment]
I believe you can get this error if you have accidentally signed out of your Google account (note that it says "Unauthenticated Use", the error should be different if you exceed your account quota). Is there a chance that is what is going on?

**Comment by ktong** [comment]
Our server is behind Google IAP. So probably token expired in IAP causes this issue. Will monitor it to get more information. Thanks

**Comment by ktong** [comment]
It's disappeared when using different oauth client it for IAP and GDrive integration

**Comment by ian-r-rose** [comment]
Glad to hear it, thanks for following up.
