### ISSUE TITLE
Google Team Drives

### ISSUE THREAD

**Issue by benvddriessche** [jupyterlab/jupyterlab-google-drive#47]
Are there any plans to enable the new Team Drive functionality (https://gsuite.google.com/learning-center/products/drive/get-started-team-drive) in the Jupyter G Drive extension?

**Comment by ian-r-rose** [comment]
This is a good idea.

**Comment by ian-r-rose** [comment]
Hi @benvddriessche , `@jupyterlab/google-drive` v0.6.0 has been released, with initial support for team drives. I don't have much experience with the semantics/use of the feature, so feedback and PRs are welcome.

**Comment by ian-r-rose** [comment]
Addressed in #54. If this does not fit your needs, feel free to reopen and continue the discussion.
