### ISSUE TITLE
Sync lost when pasting multiple cells

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab-google-drive#50]
To reproduce:

1. Edit a shared file
2. Paste several cells at once.

In the notebook edited by the person that did not perform the paste, empty cells appear. Further edit attempts result in no action.

Versions: `@jupyterlab/google-drive@0.5.0`, jupyterlab 0.26.5.

**Comment by ian-r-rose** [comment]
Thanks for the report, @akhmerov . This does indeed sound like a serious bug. Do you see this happening for pasting between notebooks, or within a single notebook?

**Comment by akhmerov** [comment]
Between a local notebook and a drive-synced notebook specifically.

**Comment by ian-r-rose** [comment]
@akhmerov, I have not forgotten about this, though I have had a hard time reproducing. A true fix likely will have to wait for the model refactor currently underway in the core `JupyterLab`.

**Comment by ian-r-rose** [comment]
Hi @akhmerov  , we have just released JupyterLab 0.28 and jupyterlab-google-drive 0.7. It may be the case that this was fixed by jupyterlab/jupyterlab#3086 . Any chance you could check if this failure is still happening?

**Comment by akhmerov** [comment]
Indeed, the issue seemingly disappeared.

**Comment by ian-r-rose** [comment]
Great, thanks for checking.
