### ISSUE TITLE
[Feature request]Support Save as to GDrive

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#52]
Got a empty untitle file while saving as to GDrive:My Drive/test.ipynb

**Comment by ktong** [comment]
undefined contents.name causes save as does not work. I tries to set it in uploadFile but contents.name is readonly. Where is best place to set contents.name? Or we just use contents.name || pathExt.basename(contents.path)

**Comment by ian-r-rose** [comment]
I think there is another issue with the error handling (one that is my fault). JupyterLab checks if a file with the same name already exists, and if it does not (i.e., `404 error`), then proceeds with the upload. The `google-drive` plugin is not currently throwing the correct error codes.

**Comment by ktong** [comment]
yes, Google drive returns **"files": []** with 200 status if file does not exist. However, google-drive plugin's save works well with code below:
```
//The file does not exist already, create a new one.
      return drive.uploadFile(path, options, fileType, false);
```

**Comment by ian-r-rose** [comment]
One problem with `Save as...` that we need to address is actually pretty similar to the issue in #64 . That is to say we need to work out the semantics of identifying changes of the underlying serialized file and updating the realtime model in response.
