### ISSUE TITLE
How to change settings

### ISSUE THREAD

**Issue by cedricyau** [jupyterlab/jupyterlab-google-drive#60]
I'm trying to enable the clientId setting for Google API and can't seem to edit the settings or save the override through the front end.

Is there a directory I can go to change the settings?

Thanks.

**Comment by cedricyau** [comment]
Looks like there was a newline character at the end of the clientId when I copied it from the Google API page.  Removing the newline allowed me to save (with an appearing checkmark).

**Comment by ian-r-rose** [comment]
Glad to hear it.

**Comment by ian-r-rose** [comment]
Is this working for you now? We welcome feedback on how to make the documentation for this clearer :)

**Comment by cedricyau** [comment]
Unfortunately, different issue now...#61.  

https://github.com/jupyterlab/jupyterlab-google-drive/issues/61
