### ISSUE TITLE
400 Error (Non localhost server)

### ISSUE THREAD

**Issue by cedricyau** [jupyterlab/jupyterlab-google-drive#61]
I have the clusterId now configured.  However, in the console, it seems that after loading, the page attempts to load:

`https://accounts.google.com/o/oauth2/iframerpc?action=listSessions&client_id=54483249296-1mgtlmhkcdon69mr0jhsahrf3vkhtnis.apps.googleusercontent.com&origin=http%3A%2F%2Fec2-54-159-216-233.compute-1.amazonaws.com&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&ss_domain=http%3A%2F%2Fec2-54-159-216-233.compute-1.amazonaws.com`

Results in a 400 Error:
`{
  "error" : "invalid_request",
  "error_description" : "Permission denied to generate login hint for target domain."
}`

**Comment by ian-r-rose** [comment]
I have not seen this error specifically before, but stackoverflow suggests that you need to add the authorized origin as a URL, and not as an IP address. Might that be the problem?

**Comment by cedricyau** [comment]
Origin is: http://ec2-54-159-216-233.compute-1.amazonaws.com.

![image](https://user-images.githubusercontent.com/6124063/29728869-c3ceca56-89a7-11e7-920c-595896579dc5.png)

**Comment by cedricyau** [comment]
It appears that the URL that is returning the error has the header: 
`Request URL:https://accounts.google.com/o/oauth2/iframe`

Maybe an iframe isn't loading?

**Comment by ian-r-rose** [comment]
It can be the case that popup blockers and cookie blockers can prevent the login from working.

**Comment by ian-r-rose** [comment]
If you are blocking third-party cookies, you may need to whitelist `accounts.google.com`.
For instance, in Chrome you would need to add it to the "Allow" section of `chrome://settings/content/cookies`

**Comment by cedricyau** [comment]
I don't have a cookie blocker that I'm aware of...

However, privacy mode seemed to get me one step further.  Error now is in a window when I try to login.

![image](https://user-images.githubusercontent.com/6124063/29729458-38130cb8-89aa-11e7-8387-9c67d5ea3afe.png)

**Comment by ian-r-rose** [comment]
Do you need the redirect URI? What happens if you remove that?

**Comment by cedricyau** [comment]
Removing that helps.  It's not necessary.

I was able to get everything running by creating a new third level domain like jupyterlab.mycompany.org.

Apparently, the issue may be with the use of ec2 automatic domains like ec2-54-159-216-233.compute-1.amazonaws.com.

**Comment by ian-r-rose** [comment]
Great, glad you got it working. Adding the reference tag to this issue in case anyone else runs into this problem.

**Comment by cedricyau** [comment]
thanks for you help ian. :)
