### ISSUE TITLE
[Feature request] Merge file content when it's changed by other application

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#64]
Steps:
  1. Open a GDrive file in JupyterLab.
  2. Change the file in local mac and sync up to GDrive.
  3. Download the File from GDrive website to confirm the change saved to GDrive.
  4. Go back to JupyterLab and reopen the file, the content does not refresh the change.
  5. Go back to GDrive website and the change has been roll back to version in JupyterLab.

Expect:
  The change has been merged and refreshed in JupyterLab.

**Comment by ian-r-rose** [comment]
Thanks for the report, @ktong. You are right, and this behavior is the result of the interaction between the realtime-aware version of a file and the serialized version. In general, it is difficult to know when the serialized version has been updated (i.e., merged from outside of the JupyterLab UI). Without this information, it is tough to know when to update the realtime version.

One possibility would be to provide an option to turn of realtime capabilities. If it is not necessary for a given deployment, then many of the upload/download semantics become easier, and we can always operate off of the serialized version.

**Comment by ktong** [comment]
Thanks, @ian-r-rose. Turn off the realtime collaboration sounds reasonable if it's hard to merge changes.

**Comment by ian-r-rose** [comment]
This is no longer an issue now that realtime Google Drive apps are no longer working.
