### ISSUE TITLE
[discuss] Use JupyterLab as Google Drive App

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#65]
I would like to configure JupyterLab as [Google Drive App](https://developers.google.com/drive/v3/web/enable-sdk). However, [this issue](https://github.com/jupyterlab/jupyterlab/issues/1075) seems blocking it. Any workaround or I have to wait the issue gets fixed.

**Comment by ian-r-rose** [comment]
This would be very cool. You are right that (this)[https://github.com/jupyterlab/jupyterlab/issues/1075] is currently a blocker.
Another problem is that the URL constructed by Google would be based upon the file ID (if I understand the docs correctly). You would need to map the file ID to the correct file for use in the `ContentsManager`. I don't really know a good workaround at the moment, but I will think about it.
