### ISSUE TITLE
[Usability] do not pop up dialog when internal error on gDrive

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#66]
Sometimes, requests to google drive return 500 (Internal Error), which causes JupyterLab pop up a dialog. It's annoy to user because user can do nothing on this expects close it. It's probably better to retry it instead of popping up dialog.

**Comment by ian-r-rose** [comment]
Yep, absolutely right!

**Comment by ian-r-rose** [comment]
Fixed by #67, jupyterlab/jupyterlab#3052
