### ISSUE TITLE
Allow origin to be configurable.

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab-google-drive#7]
In order to use the Google APIs you need to specify the origin that it expects, otherwise it will reject any requests with an error along the lines of
```
Refused to display 'https://accounts.google.com/o/oauth2/...' in a frame because it set 'X-Frame-Options' to 'sameorigin'
```
Currently, we are configured to accept `http://localhost`, ports `8888` through `8899`. This option should be configurable, with documentation for how to set up your own client ids.

**Comment by Analect** [comment]
Thanks @ian-r-rose .
It would be useful to get this working in the context of jupyterhub too.  So while the notebook is generally started using port `8888` ... there is a proxy  running as part of the architecture too.  I don't know whether that complicates things or not.

**Comment by ktong** [comment]
Has same issue when deploying in JupyterHub. May I use my own client_id for google OAuth?

**Comment by ian-r-rose** [comment]
Yes, thought it is currently hard-coded, so you would need to go into `src/gapi.ts` to change it.

**Comment by ktong** [comment]
Do you mean I need fork this repo and change in src/gapi.ts? is there any way I can change it after installing with jupyter labextension install @jupyterlab/google-drive

**Comment by blink1073** [comment]
The brute force way would be to edit the shipped file in the JupyterLab app dir, in `staging/node_modules/@jupyterlab/google-drive/lib/gapi.js`, where the app dir is found using `jupyter lab path`.

**Comment by blink1073** [comment]
(and then run `jupyter lab build` again).

**Comment by ian-r-rose** [comment]
All that being said, the settings system has landed in JupyterLab master, so this should be configurable for the next release.

**Comment by ktong** [comment]
cool. I will use brute force way now until next release. thank you both

**Comment by ktong** [comment]
brute force way:
sed -i s/625147942732-t30t8vnn43fl5mvg1qde5pl84603dr6s.apps.googleusercontent.com/${OAUTH_CLIENT_ID}/g /srv/venv/share/jupyter/lab/static/main.bundle.js* &&
sed -i s/625147942732/$(echo $OAUTH_CLIENT_ID | cut -d'-' -f 1)/g /srv/venv/share/jupyter/lab/static/main.bundle.js*

**Comment by ian-r-rose** [comment]
This has been fixed in v0.2.0 via #13. At the moment, the setting system is client-side, which is not the best solution (we would like it to be able to be set from the server side), but it works for the time-being until we have server-side settings up and running.

**Comment by ktong** [comment]
I set clientId into setting/page-config.json and it does not work. Cannot find more doc for how to set it. Any hints?

**Comment by ian-r-rose** [comment]
At the moment the settings are stored only in `localStorage`, so you have to edit the `clientId` within the JupyterLab settings editor.  It is still not a great solution, but should work. After we implement a server-side settings datastore, this should be simpler (and easier to deploy).

**Comment by ktong** [comment]
Got it. Stick on brute force.

**Comment by ian-r-rose** [comment]
@ktong The most recent releases of JupyterLab (`v0.26`) and jupyterlab-google-drive (`v0.5) have a server-side settings system, so it should no longer be necessary to use the `sed` trick.

**Comment by ktong** [comment]
cool. Will try it later. Thanks

**Comment by barche** [comment]
Just to be explicit: it seems the settings go into `/home/jovyan/.jupyter/lab/user-settings/jupyter.extensions.google-drive.json` when extending the standard jupyter Docker image. Works like a charm!

**Comment by Analect** [comment]
@barche  ... I'm trying to get this working.  Could you post what your `jupyter.extensions.google-drive.json` looks like (obfuscating anything sensitive, obviously) and are you injecting this file automatically as part of a docker image creation which then gets used for spawning a jupyterlab server?  

Presumably this is a way of pre-setting the clientId rather than setting it manually in the app on start-up, as per below?

![image](https://user-images.githubusercontent.com/4063815/28576977-4996294a-714d-11e7-9cae-cfb2008c6d36.png)

If your jupyterlab gets launched via jupyterhub, what uri do you end up white-listing back on the google developers console?  I'm running jupyterhub on kubernetes and expose a `proxy-public` service, but using this ip doesn't appear to work.

Thanks.

**Comment by ktong** [comment]
@Analect I use postStart lifecycle executing command 
```
echo "{\"clientId\":\"${OAUTH_CLIENT_ID}\"}" > /home/vellum/.jupyter/lab/user-settings/jupyter.extensions.google-drive.json
```
 to create jupyter.extensions.google-drive.json which contains {"clientId": "your google clientId"}.

Are you using ip to access your Jupyterhub?  Google OAuth redirect urls do not support ip. 

> Authorized redirect URIs
For use with requests from a web server. This is the path in your application that users are redirected to after they have authenticated with Google. The path will be appended with the authorization code for access. Must have a protocol. Cannot contain URL fragments or relative paths. Cannot be a public IP address.

**Comment by barche** [comment]
@Analect Yes, I am creating a Docker image with this. The relevant parts from the Dockerfile are:

```Dockerfile
FROM jupyter/scipy-notebook
USER jovyan

RUN pip3 install -U jupyterlab
RUN jupyter labextension install @jupyterlab/google-drive
COPY jupyter.extensions.google-drive.json /home/jovyan/.jupyter/lab/user-settings/
```
The json file contains the single line (fake ID):
```json
{"clientId": "123456781234-pt599f2ppb6rwtgxipyokzqdqamfcrv3.apps.googleusercontent.com"}
```
On the Google Developer Console, you need to add the public address of your server (e.g. https://jupyterhub.mysite.com)

**Comment by ian-r-rose** [comment]
Reopening as this is a useful discussion. Thanks all!

**Comment by Analect** [comment]
@barche ... thanks for clarifying.  Thanks also @ktong 

I was following those steps ... although adding the clientId within settings manually on JupyterLab 0.26.3 for now ... and not rebuilding anything after adding ... just merely reloading the web page (refreshing cache) ... which may or may not be the right approach.

![image](https://user-images.githubusercontent.com/4063815/28592242-4ab6e4a8-7180-11e7-8131-3587676f6b54.png)

Eventhough I have added `http://jupyterlab.myserver.com` (not real uri), as per above, to the developer console (this is the DNS of my public proxy running as part of jupyterhub set-up on kubernetes), for some reason I'm still not getting things to work.  Is there any requirement for it to be `https` (as I have just `http` running currently).  I'm using GitLab (as opposed to GitHub) as an authenticator for the hub ... I'm not sure whether the use of an authenticator should affect this or not.  It obviously doesn't affect the functioning of JupyterLab itself.

![image](https://user-images.githubusercontent.com/4063815/28592698-c77641f4-7181-11e7-8df7-2eca23105383.png)

**Comment by barche** [comment]
I don't know why it's not working, though I do use https. Other than that, adding the id manually and then reloading the webpage should be enough to get it to load. The hub authenticator has nothing to do with it, indeed.

**Comment by ian-r-rose** [comment]
I am also not sure what the problem is, @Analect. Are you serving over a nonstandard port? If so, the port also needs to be included in the list of authorized origins.

**Comment by Analect** [comment]
@ian-r-rose ... thanks.  It seems to have resolved itself ... I think I hadn't enabled pop-ups in chrome ... and that was somehow suppressing things.

**Comment by ian-r-rose** [comment]
Glad to hear it.

**Comment by ian-r-rose** [comment]
Closing for now. The user experience for setting up a client ID can still be improved, but it seems to work correctly in a number of different contexts.
