### ISSUE TITLE
Photos or Video Link in README?

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab-google-drive#72]
@ian-r-rose I like the use of photos in the readme? Should we consider also including photos on basic tasks like sharing and chat? Or perhaps link to the timestamped part of one of our talks?

**Comment by ian-r-rose** [comment]
Yes, I think this is a good idea.

**Comment by jzf2101** [comment]
https://youtu.be/dSjvK-Z3o3U?t=13m4s

**Comment by jzf2101** [comment]
I've put a version of the readme with your talk from pydata seattle as a start @ian-r-rose

**Comment by willingc** [comment]
@jzf2101 As an fyi, nbgrader has used gif and photos well in their docs.

**Comment by jzf2101** [comment]
@willingc do you have recommendations on making gifs in photoshop? I'm going through an online tutorial but I can't get my previews to work

**Comment by willingc** [comment]
@jzf2101 Jess Hamrick and I use licecap (horrible name but works well). I believe it works on all os.

**Comment by ian-r-rose** [comment]
Resolved by #73.
