### ISSUE TITLE
Can't open "My Drive" with german account

### ISSUE THREAD

**Issue by Gusser93** [jupyterlab/jupyterlab-google-drive#80]
If I try to open "My Drive" ("Meine Ablage" in German) with a German google account I get a
```
Server Connection Error
Unexpected file in root directory: Meine Ablage
```
If I switch my language in google to English, everything seems to work fine.
I'm using jupyterlab 0.27.0 on Ubuntu 16.04.3 in Firefox 57.0b4 (64-bit).

**Comment by ian-r-rose** [comment]
Thanks for the report! We definitely shouldn't be assuming English for the root Google Drive name.
