### ISSUE TITLE
[Feature Request] refreshAuthToken while gapi returns 401

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#87]
Currently, it only refreshes auth token using timer. However, when I close my mac and reopen it in 1 hour, I get 401 (Invalid Credentials) from gapi util timer works again. Is it possible to refresh auth token after getting 401 from gapi?

**Comment by ian-r-rose** [comment]
Good idea! We should investigate how easy this is to do. It may be as simple as handling that case in `driveApiRequest` [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/src/gapi.ts#L182)

**Comment by ktong** [comment]
It's even better if it retries after refreshAuthToken

**Comment by ian-r-rose** [comment]
Agreed.

**Comment by ian-r-rose** [comment]
I have just submitted #88 which addresses this. You will still see errors regarding a lost connection, but in my experiments it removes the need to refresh the page or log out.

**Comment by ktong** [comment]
Cool. Thanks. 
Any plan to release a new version?

**Comment by ian-r-rose** [comment]
We will be cutting a JupyterLab v0.28 release some time in the next week, and I will release this at around the same time.

**Comment by ian-r-rose** [comment]
We have just released JupyterLab 0.28 and jupyterlab-google-drive 0.7 which has this feature. Let me know if it works for your use case!
