### ISSUE TITLE
Empty cells when refreshing

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#91]
Steps to produce:
1. open multiple notebooks in Google drive,
2. change some cells
3. refresh(es) whole page
4. Notebook shows empty cells

### Empty Cell
<img width="784" alt="screen shot 2017-10-10 at 2 15 17 pm" src="https://user-images.githubusercontent.com/4332577/31412499-35f5c24c-adca-11e7-9037-0d386954e58e.png">

### Normal cell
<img width="784" alt="screen shot 2017-10-10 at 2 15 39 pm" src="https://user-images.githubusercontent.com/4332577/31412533-4f6a3352-adca-11e7-9e0f-5519365fffce.png">

**Comment by ian-r-rose** [comment]
Thanks for the report @ktong, this is a pretty serious bug. We have just merged a fix for this, which should be released tomorrow. I will leave this open until then.

**Comment by ktong** [comment]
Cool. Thanks. I will test if after tomorrow’s release

**Comment by ian-r-rose** [comment]
Hi @ktong  , we have just released JupyterLab 0.28 and jupyterlab-google-drive 0.7 which has this fix. If you still experience this problem, feel free to reopen.
