### ISSUE TITLE
Unable to make it work on internal server

### ISSUE THREAD

**Issue by jochym** [jupyterlab/jupyterlab-google-drive#93]
I was trying to make the extension work on our internal jupyterhub server. It is only accessible over VPN and does not have any public IP. I have followed the advanced setup wiki but at the end it did not show any folders (just empty pane with gdrive logo in it). The log-in worked but thats it. The log-out icon never showed up as well. I was able to make it work by removing ClientId overwrite and tunneling the connection over ssh from localhost:8888 to the correct port on the server. So the install is ok - just the set of permissions/services enabled on my google API account is probably not correct.
Is it possible that the Advanced setup wiki page is incorrect/outdated?

**Comment by ian-r-rose** [comment]
The advanced setup should be up-to-date, but we have not done any testing for a hub over a VPN, so it is possible there is some trick to it.

Does your setup work over `localhost:8888` if you add that to the list of authorized origins? That would help to verify that you have set up the rest of the Google Drive application correctly.

**Comment by jochym** [comment]
I am not 100% sure but I think it does not. I cannot restart the server at this moment but I will get back to you when I test it on the staging install. Unfortunately I am afraid I will have no time for this in the next few days. Is there anything more I should test?

**Comment by ian-r-rose** [comment]
The main things I can think of at the moment:
1. Try it locally, rather than on your server (after adding `localhost` to the authorized origins). This would let us know that the APIs and permissions are properly enabled.
2. If there are any errors going to the Javascript console, that would be useful to know.

**Comment by jochym** [comment]
OK. Will get back to you.

**Comment by cforelle** [comment]
@jochym, what port is the internal JupyterHub server running on? I wonder if this is similar to #94

**Comment by jochym** [comment]
It is running on standard https (443)  but I can test it on multiple ports by tunneling. I'll run the other promised tests today.

**Comment by jochym** [comment]
I have checked it with the local install. If I run it with default config (i.e. project api credentials) everything works. If I switch to my credentials (by adding my clientId override) and no other change it stops working and I get the Google API error: Not a valid origin for the client: http://localhost:8889 has not been whitelisted for client ID _my_api_client_id_here ...

I'll check the JS next.

**Comment by ian-r-rose** [comment]
That error is typically shown if your Google app has a configuration
problem (see doc/troubleshooting.md). Have you added localhost:8889 to your
list of authorized domains?

**Comment by jochym** [comment]
That is what I suspect - I am reviewing (again) the setup step by step right now. Maybe I have missed something. I'll be grateful for any debugging ideas.

**Comment by jochym** [comment]
http://localhost:8889 is on the "Authorised JavaScript origins" list. The problem is the api console shows no info. I have only three APIs running: Drive, Picker, Realtime. No requests/errors are logged at all.

**Comment by jochym** [comment]
I've checked all the settings in advanced.md - everything seems in order. But I found one hint/difference. If I run locally in google chrome all is fine. I can switch back and forth between clientIds and the app keeps working. If I do it on remote session (https://10.0.1.100/) it stops working but without the dialog with API error end with tab with just the logo - no sign in or content. Via ssh tunnel over port 8888 it still works. I'll check an upper remote port next.

**Comment by jochym** [comment]
I have checked the remote by forwarding port 8888 to 443 and got the API error dialog even in chrome. So still no progress. I have my jupyterhub set up to work over https and automatically redirect to https. Maybe this is a problem?

**Comment by ian-r-rose** [comment]
Do you mean redirect http to https? It might be a problem, I think the protocol matters for matching the authorized origin.

**Comment by jochym** [comment]
Yes. If I try to connect over http the session gets redirected automatically to https. But I always explicitly connect to https://IP/ so there should be no magic on the way. I use pretty standard install and my use case should be fairly common (jupyterhub running on internal server accessed over openvpn, mostly installed from conda packages on minimal debian system). I can provide any config info required for debugging.

**Comment by jochym** [comment]
Current state is:
1. I can reliably work with my API Id over ssh tunnel localhost:8888 -> server_localhost:443
2. The same is true with localhost:8888 -> server_ip:443 tunnel (ip from 10.x.x.x range)
3. Direct connection to https://server_ip does not work, but shows google drive logo without sign-in button and **does not** show API error dialog.
I'm out of ideas for now. The only remaining idea I have is to make a test deployment without jupyterhub and test it there. It is a bit of work but can be done if necessary. Please check if I can test anything more before I start doing that.

**Comment by cforelle** [comment]
In scenario 3, do you see any errors in the browser JavaScript console?

**Comment by ian-r-rose** [comment]
Hi @jochym, thanks for the detailed report. I will try to reproduce your setup (as near as I can) next week to see if I can figure out what is going on.

**Comment by jochym** [comment]
Yes it does - No session bound error. Shell I check something more? I'll read https://github.com/jupyterlab/jupyterlab-google-drive/issues/94 more carefully and try to extract something myself as well.

**Comment by cforelle** [comment]
I don’t have any concrete suggestions, but as I’m trying to chase down a similar problem, I’d be curious to know:
 
-if it is possible to have the server on another port, say 8443 (or 8888), do you still get the noSessionBound error?
-Alternatively, if you can’t change the server port, what if you tunnel localhost:443 to server_ip:443?

(Adding those origins in Google Dev Console for your clientid, of course.)

**Comment by jochym** [comment]
I'll try and report shortly.

**Comment by jochym** [comment]
@cforelle 

1. I have made the next close thing - I have forwarded 8443 -> 443 _on the server_ and it **worked**! 
2. If I tunnel localhost:443 -> server:443 it does __not__ work

So I have at least a functional workaround for the issue - but it is seems to be connected with the port used on the local machine. If it is 443 it fails.

**Comment by cforelle** [comment]
@jochym thanks. So for (1) you are going to https://server_ip:8443 in the browser, and https://server_ip:8443 is whitelisted in Google Dev Console?

I agree that (2) and (3) suggest it is an issue with the port. Exactly what, I’m not sure.

**Comment by ian-r-rose** [comment]
Hi @jochym , @cforelle . I have pushed a branch of the extension with a potential fix for this and #94 [here](https://github.com/jupyterlab/jupyterlab-google-drive/tree/resolve_nosessionbound). If you get the chance, would you be able to install that branch to see if it resolves the issue?

**Comment by ian-r-rose** [comment]
Great! This messes with authorization refresh a bit, so I am still chasing down a workaround, but once I nail that down we can publish a patch release with this fix.

**Comment by ian-r-rose** [comment]
Hi @jochym, it took a little longer than I anticipated to figure out a workaround, but I have just published `v0.8.0`, which includes the fix for this. Let me know if that works for your use case.

**Comment by ian-r-rose** [comment]
Closed by #97.

**Comment by jochym** [comment]
Thanks. It seems to be working fine now.
