### ISSUE TITLE
location of clientId user-settings appears to have changed

### ISSUE THREAD

**Issue by Analect** [jupyterlab/jupyterlab-google-drive#98]
@ian-r-rose 
I was having trouble getting the jupyterlab-google-drive extension working against v. 0.28.12 of jupyterlab.

Previously, I was adding a file containing a `clientId` by the name of `jupyter.extensions.google-drive.json` into `/home/jovyan/.jupyter/lab/user-settings`.  However, this no longer appears to get picked-up.

I then decided to add the credentials manually via jupyterlab and it ended up saving these to `/home/jovyan/.jupyter/lab/user-settings/@jupyterlab/google-drive/drive.json`.

Can you confirm if this is the new permanent home for settings for this extension?  If so, then perhaps something should get added to the docs, since there are various references to the earlier location scattered in issues throughout this repo.

**Comment by Analect** [comment]
@ian-r-rose  ... I can try to add a section to the `docs/advanced.md` document via a PR, if you like.  Or would you prefer something in the main `README.md`?

**Comment by ian-r-rose** [comment]
That would be much appreciated! I think that `docs/advanced.md` is the appropriate place.
